{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "olb.fullname" . }}
  labels:
    {{- include "olb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "olb.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: admin
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
